# Generated by Django 4.0.6 on 2022-07-27 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0005_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
